FROM python:3.9

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /startup
COPY docker/gulp_build/entrypoint.build_ui.sh .

VOLUME /django-jet-reboot

ENTRYPOINT [ "/bin/bash", "entrypoint.build_ui.sh" ]